insert into dido.Country (country) values ("Afghanistan");
insert into dido.Country (country) values ("Albania");
insert into dido.Country (country) values ("Algeria");
insert into dido.Country (country) values ("Andorra");
insert into dido.Country (country) values ("Angola");
insert into dido.Country (country) values ("Antigua and Barbuda");
insert into dido.Country (country) values ("Argentina");
insert into dido.Country (country) values ("Armenia");
insert into dido.Country (country) values ("Australia");
insert into dido.Country (country) values ("Austria");
insert into dido.Country (country) values ("Azerbaijan");
insert into dido.Country (country) values ("Bahamas");
insert into dido.Country (country) values ("Bahrain");
insert into dido.Country (country) values ("Bangladesh");
insert into dido.Country (country) values ("Barbados");
insert into dido.Country (country) values ("Belarus");
insert into dido.Country (country) values ("Belgium");
insert into dido.Country (country) values ("Belize");
insert into dido.Country (country) values ("Benin");
insert into dido.Country (country) values ("Bhutan");
insert into dido.Country (country) values ("Bolivia");
insert into dido.Country (country) values ("Bosnia and Herzegovina");
insert into dido.Country (country) values ("Botswana");
insert into dido.Country (country) values ("Brazil");
insert into dido.Country (country) values ("Brunei");
insert into dido.Country (country) values ("Bulgaria");
insert into dido.Country (country) values ("Burkina Faso");
insert into dido.Country (country) values ("Burundi");
insert into dido.Country (country) values ("Cabo Verde");
insert into dido.Country (country) values ("Cambodia");
insert into dido.Country (country) values ("Cameroon");
insert into dido.Country (country) values ("Canada");
insert into dido.Country (country) values ("Central African Republic");
insert into dido.Country (country) values ("Chad");
insert into dido.Country (country) values ("Chile");
insert into dido.Country (country) values ("China");
insert into dido.Country (country) values ("Colombia");
insert into dido.Country (country) values ("Comoros");
insert into dido.Country (country) values ("Democratic Republic of the Congo");
insert into dido.Country (country) values ("Republic of the Congo");
insert into dido.Country (country) values ("Costa Rica");
insert into dido.Country (country) values ("Cote d'Ivoire");
insert into dido.Country (country) values ("Croatia");
insert into dido.Country (country) values ("Cuba");
insert into dido.Country (country) values ("Cyprus");
insert into dido.Country (country) values ("Czech Republic");
insert into dido.Country (country) values ("Denmark");
insert into dido.Country (country) values ("Djibouti");
insert into dido.Country (country) values ("Dominica");
insert into dido.Country (country) values ("Dominican Republic");
insert into dido.Country (country) values ("Ecuador");
insert into dido.Country (country) values ("Egypt");
insert into dido.Country (country) values ("El Salvador");
insert into dido.Country (country) values ("Equatorial Guinea");
insert into dido.Country (country) values ("Eritrea");
insert into dido.Country (country) values ("Estonia");
insert into dido.Country (country) values ("Ethiopia");
insert into dido.Country (country) values ("Fiji");
insert into dido.Country (country) values ("Finland");
insert into dido.Country (country) values ("France");
insert into dido.Country (country) values ("Gabon");
insert into dido.Country (country) values ("Gambia");
insert into dido.Country (country) values ("Georgia");
insert into dido.Country (country) values ("Germany");
insert into dido.Country (country) values ("Ghana");
insert into dido.Country (country) values ("Greece");
insert into dido.Country (country) values ("Grenada");
insert into dido.Country (country) values ("Guatemala");
insert into dido.Country (country) values ("Guinea");
insert into dido.Country (country) values ("Guinea-Bissau");
insert into dido.Country (country) values ("Guyana");
insert into dido.Country (country) values ("Haiti");
insert into dido.Country (country) values ("Honduras");
insert into dido.Country (country) values ("Hungary");
insert into dido.Country (country) values ("Iceland");
insert into dido.Country (country) values ("India");
insert into dido.Country (country) values ("Indonesia");
insert into dido.Country (country) values ("Iran");
insert into dido.Country (country) values ("Iraq");
insert into dido.Country (country) values ("Ireland");
insert into dido.Country (country) values ("Israel");
insert into dido.Country (country) values ("Italy");
insert into dido.Country (country) values ("Jamaica");
insert into dido.Country (country) values ("Japan");
insert into dido.Country (country) values ("Jordan");
insert into dido.Country (country) values ("Kazakhstan");
insert into dido.Country (country) values ("Kenya");
insert into dido.Country (country) values ("Kiribati");
insert into dido.Country (country) values ("Kosovo");
insert into dido.Country (country) values ("Kuwait");
insert into dido.Country (country) values ("Kyrgyzstan");
insert into dido.Country (country) values ("Laos");
insert into dido.Country (country) values ("Latvia");
insert into dido.Country (country) values ("Lebanon");
insert into dido.Country (country) values ("Lesotho");
insert into dido.Country (country) values ("Liberia");
insert into dido.Country (country) values ("Libya");
insert into dido.Country (country) values ("Liechtenstein");
insert into dido.Country (country) values ("Lithuania");
insert into dido.Country (country) values ("Luxembourg");
insert into dido.Country (country) values ("Macedonia");
insert into dido.Country (country) values ("Madagascar");
insert into dido.Country (country) values ("Malawi");
insert into dido.Country (country) values ("Malaysia");
insert into dido.Country (country) values ("Maldives");
insert into dido.Country (country) values ("Mali");
insert into dido.Country (country) values ("Malta");
insert into dido.Country (country) values ("Marshall Islands");
insert into dido.Country (country) values ("Mauritania");
insert into dido.Country (country) values ("Mauritius");
insert into dido.Country (country) values ("Mexico");
insert into dido.Country (country) values ("Micronesia");
insert into dido.Country (country) values ("Moldova");
insert into dido.Country (country) values ("Monaco");
insert into dido.Country (country) values ("Mongolia");
insert into dido.Country (country) values ("Montenegro");
insert into dido.Country (country) values ("Morocco");
insert into dido.Country (country) values ("Mozambique");
insert into dido.Country (country) values ("Myanmar");
insert into dido.Country (country) values ("Namibia");
insert into dido.Country (country) values ("Nauru");
insert into dido.Country (country) values ("Nepal");
insert into dido.Country (country) values ("Netherlands");
insert into dido.Country (country) values ("New Zealand");
insert into dido.Country (country) values ("Nicaragua");
insert into dido.Country (country) values ("Niger");
insert into dido.Country (country) values ("Nigeria");
insert into dido.Country (country) values ("North Korea");
insert into dido.Country (country) values ("Norway");
insert into dido.Country (country) values ("Oman");
insert into dido.Country (country) values ("Pakistan");
insert into dido.Country (country) values ("Palau");
insert into dido.Country (country) values ("Palestine");
insert into dido.Country (country) values ("Panama");
insert into dido.Country (country) values ("Papua New Guinea");
insert into dido.Country (country) values ("Paraguay");
insert into dido.Country (country) values ("Peru");
insert into dido.Country (country) values ("Philippines");
insert into dido.Country (country) values ("Poland");
insert into dido.Country (country) values ("Portugal");
insert into dido.Country (country) values ("Qatar");
insert into dido.Country (country) values ("Romania");
insert into dido.Country (country) values ("Russia");
insert into dido.Country (country) values ("Rwanda");
insert into dido.Country (country) values ("Saint Kitts and Nevis");
insert into dido.Country (country) values ("Saint Lucia");
insert into dido.Country (country) values ("Saint Vincent and the Grenadines");
insert into dido.Country (country) values ("Samoa");
insert into dido.Country (country) values ("San Marino");
insert into dido.Country (country) values ("Sao Tome and Principe");
insert into dido.Country (country) values ("Saudi Arabia");
insert into dido.Country (country) values ("Senegal");
insert into dido.Country (country) values ("Serbia");
insert into dido.Country (country) values ("Seychelles");
insert into dido.Country (country) values ("Sierra Leone");
insert into dido.Country (country) values ("Singapore");
insert into dido.Country (country) values ("Slovakia");
insert into dido.Country (country) values ("Slovenia");
insert into dido.Country (country) values ("Solomon Islands");
insert into dido.Country (country) values ("Somalia");
insert into dido.Country (country) values ("South Africa");
insert into dido.Country (country) values ("South Korea");
insert into dido.Country (country) values ("South Sudan");
insert into dido.Country (country) values ("Spain");
insert into dido.Country (country) values ("Sri Lanka");
insert into dido.Country (country) values ("Sudan");
insert into dido.Country (country) values ("Suriname");
insert into dido.Country (country) values ("Swaziland");
insert into dido.Country (country) values ("Sweden");
insert into dido.Country (country) values ("Switzerland");
insert into dido.Country (country) values ("Syria");
insert into dido.Country (country) values ("Taiwan");
insert into dido.Country (country) values ("Tajikistan");
insert into dido.Country (country) values ("Tanzania");
insert into dido.Country (country) values ("Thailand");
insert into dido.Country (country) values ("Timor-Leste");
insert into dido.Country (country) values ("Togo");
insert into dido.Country (country) values ("Tonga");
insert into dido.Country (country) values ("Trinidad and Tobago");
insert into dido.Country (country) values ("Tunisia");
insert into dido.Country (country) values ("Turkey");
insert into dido.Country (country) values ("Turkmenistan");
insert into dido.Country (country) values ("Tuvalu");
insert into dido.Country (country) values ("Uganda");
insert into dido.Country (country) values ("Ukraine");
insert into dido.Country (country) values ("United Arab Emirates");
insert into dido.Country (country) values ("United Kingdom (UK)");
insert into dido.Country (country) values ("United States of America");
insert into dido.Country (country) values ("Uruguay");
insert into dido.Country (country) values ("Uzbekistan");
insert into dido.Country (country) values ("Vanuatu");
insert into dido.Country (country) values ("Vatican City");
insert into dido.Country (country) values ("Venezuela");
insert into dido.Country (country) values ("Vietnam");
insert into dido.Country (country) values ("Yemen");
insert into dido.Country (country) values ("Zambia");
insert into dido.Country (country) values ("Zimbabwe");